name: Build

on:
  workflow_call:
    inputs:
      node-version:
        default: 16.x
        required: false
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
      
      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Cache Build Artifact
        id: build-cache
        uses: actions/cache/save@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.ref_name }}-build

