name: Main

env:
  context: './'
  cache-name: cache-release
  node-version: 16.x

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    uses: micro-lc/documentation/.github/workflows/checks.yml@main

  build:
    uses: micro-lc/documentation/.github/workflows/build.yml@main

  file-changes:
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.filter.outputs.test-files }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            test-files:
              - 'yarn.lock'
              - package.json
              - '.github/workflows/**'
              - 'tests/**'
              - 'src/**'
              - 'applications/**'

  deploy-pages:
    needs:
      - checks
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.sha }}-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  e2e-tests:
    needs:
      - build
      - file-changes
    if: needs.file-changes.outputs.test-files == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.sha }}-build

      - name: Install
        run: yarn install --immutable

      - name: Install Playwright
        run: yarn dlx playwright install --with-deps

      - name: Run your tests
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
