name: Main

env:
  context: './'
  cache-name: cache-release
  node-version: 16.x

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: micro-lc/documentation/.github/workflows/checks.yml@main

  build:
    uses: micro-lc/documentation/.github/workflows/build.yml@main

  deploy-pages:
    needs:
      - checks
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Build Artifact
        id: build-cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.ref_name }}-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  e2e-tests:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Cache Build Artifact
        id: build-cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.ref_name }}-build

      - name: Install
        run: yarn install --immutable

      - name: Install Playwright
        run: yarn dlx playwright install

      - name: Run your tests
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
