name: Main

env:
  context: './'
  cache-name: cache-release
  node-version: 16.x

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: micro-lc/documentation/.github/workflows/checks.yml@main

  build:
    uses: micro-lc/documentation/.github/workflows/build.yml@main

  deploy-pages:
    needs:
      - checks
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Build Artifact
        id: build-cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.os }}-${GITHUB_REF_NAME}-build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
